### ISSUE TITLE
ConfirmPrompt custom keybindings for Yes and No

### ISSUE THREAD

**Issue by eitchtee** [kazhala/InquirerPy#13]
Is there any plans for customizable keys for [Y]es and [N]o on ConfirmPrompt?

_E.g._ Are you sure? **(S/n)**

From an internalization standpoint it would be a good option to have as not every language uses Y and N for confirmation, despite it being the norm for CLI tools.

For example, I'm currently working on a user-facing tool in Portuguese, using this library, and the Y/n prompt creates some confusions since not everybody associates SIm (yes) and Não (No) with their English counterparts.

**Comment by kazhala** [comment]
Hi @eitchtee ,

Thanks for raising this point. It makes sense.

I'll include this in the next release.

Thanks,
Kevin

**Comment by eitchtee** [comment]
Thank you @kazhala, looking forward to it

**Comment by kazhala** [comment]
Hi @eitchtee ,

This is now in included in v0.2.3 version. Please refer to the [changelog](https://github.com/kazhala/InquirerPy/blob/master/CHANGELOG.md#added) for information on how to use and customise this behaviour.

Thanks,
Kevin
