### ISSUE TITLE
Support for answer display differing from name

### ISSUE THREAD

**Issue by rthill91** [kazhala/InquirerPy#17]
I have a case  where I'm providing additional context information in my checkbox choices that, for ease of readability, I don't want to show in the answer confirmation.

Something like 
```python3
choices = [
    {"name": "Foo | address | info | other", "value": "foo"},
    {"name": "Bar | address | info | other", "value": "bar"},
    {"name": "Baz | address | info | other", "value": "baz"},
]
```

This looks great at the prompt but if the user selects them all they'll end up with an answer/confirmation with something like

```sh
? Choose some ['Foo | address | info | other', 'Bar | address | info | other', 'Baz | address | info | other']
```

It's the options they selected but at that point the only relevant info I'd like to show is 

```sh
? Choose some ['Foo', 'Bar', 'Baz']
```

Is this by chance something already supported or something you could see adding in a future update? An additional key like `answer` I could provide when defining my choices would be ideal, but my personal case could also be served with a name->answer transformer I could define

**Comment by kazhala** [comment]
Hi @rthill91 ,

This feature currently exists, each prompt support an additional argument called `transformer` which should be a function that takes an argument (name or list of names of the choices) and will be up to you to perform additional logic to change the visual that displays.

It is documented [here](https://github.com/kazhala/InquirerPy/wiki/CheckboxPrompt#transformer-callableany-any).
And [here](https://github.com/kazhala/InquirerPy/blob/5be989ada6362bdfa31832a8905cdee0cb60a634/examples/example_checkbox.py#L56-L57) is another example.

This has been done a while ago but I can't recall the reason why it only receives the `name` of the choice....let me know if receiving the entire choice would be ideal or more deal-breaking (Might need to be a BREAK_CHANGE).

Apologies if the doc is not very obvious, I'm planning to migrate/upgrade the doc in the near future, stay tuned...

Thanks,
Kevin

**Comment by kazhala** [comment]
In your case with the current behaviour of the transformer, you might have to do some string processing in the `transformer` function. If you are using the classic syntax it would be the same principal.

```python
from InquirerPy import inquirer

result = inquirer.checkbox(
    message="Choose some",
    choices=[
        {"name": "Foo | address | info | other", "value": "foo"},
        {"name": "Bar | address | info | other", "value": "bar"},
        {"name": "Baz | address | info | other", "value": "baz"},
    ],
    transformer=lambda result: [name.split(" | ")[0] for name in result],
).execute()
```

The above will produce the UI like the following.

```
? Choose some ['Foo', 'Bar', 'Baz']
```

**Comment by rthill91** [comment]
Reading comprehension failed me. I saw the transformer option and for some reason had it in my head that it affected the value, not the name. Thanks for the help!
