### ISSUE TITLE
How to determine pressed key from keybinding with multiple keys

### ISSUE THREAD

**Issue by robvanderleek** [kazhala/InquirerPy#27]
I would like to know which key was pressed if a keybinding has multiple keys configured.

This is a simplified use-case:
```python
from InquirerPy import inquirer

choice = inquirer.select(message='Select item:', choices=['foo', 'bar'],
                         keybindings={
                             "answer": [{"key": "enter"}, {"key": "d"}],
                         },
                         long_instruction='ENTER=view, D=delete').execute()
print(choice)
```
How can I determine if the user pressed [enter] or [d]?
Any alternative solutions are also appreciated!

Thanks for maintaining this great library!

**Comment by kazhala** [comment]
Hi @robvanderleek ,

It does not export the key being pressed. However, I think usecases like this it's more reasonable to create custom keybindings.

Doc: [link](https://inquirerpy.readthedocs.io/en/latest/pages/kb.html#binding-custom-functions)

```python
from InquirerPy import inquirer

prompt = inquirer.select(
    message="Select item:",
    choices=["foo", "bar"],
    long_instruction="ENTER=view, D=delete",
)

@prompt.register_kb("d")
def _handle_delete(event):
    choice_name = prompt.result_name
    choice_value= prompt.result_value
    # do something here to delete it
    # ...
    # you can then use the event API to exit the app with None value
    event.app.exit(result=None)
    # you can optionally delete the choice and then skip the choice which also return None value
    # Note: this will turn the prompt color to skipped color
    prompt._mandatory = False
    prompt._handle_skip(event)

result = prompt.execute()
if result is not None:
    # view logic
    pass
```

Alternativly if you want to process the deletion logic out side, you can also just `event.app.exit(result={"value": prompt.result_value, "delete": True})` and start checking result is dict or other values etc.

I hope this solution can solve your usecase. I think the custom keybinding section can definitely have a bit more example and explanation. I'll work on it.

Thanks,
Kevin

**Comment by robvanderleek** [comment]
Hi @kazhala 👋 

Thanks a lot for the quick and very helpful response.

The combination of a custom keybinding and `event.app.exit(...)` fits my use-case perfectly!

FWIW, I did read about custom keybindings in the documentation but could not figure out how to access the prompt selection and set the `execute()` return value inside the binding function, as you explained in this issue.

Again, thanks for your active maintenance of this excellent library.

Best regards, Rob
