### ISSUE TITLE
Cyclic import in select

### ISSUE THREAD

**Issue by TStrolia** [kazhala/InquirerPy#28]
I am still a bit newer to python (only a year or so) and I have been trying to put something together that really just needs a well designed CLI and this has really been an amazing tool since development on PyInquirer seems to have slowed to a near halt. InquirerPy has been amazing.

There seems to be an issue with select having a circular import. I tried to find where it was specifically but got a little lost with it. Unfortunately that is probably one of the more important things I need. I don't see a public road map covering bugs so I don't know if this is something you are already aware of or not.

**Comment by kazhala** [comment]
Hi @TStrolia ,

Thanks for using the package and reporting issues! There are not currently any other bug trackers other than this issue thread.

I'm not aware that there are any pending cyclic import issues. Could you provide a bit more details like a code-snippet around how you encountered the cyclic import so that I could reproduce it?

Thanks,
Kevin

**Comment by TStrolia** [comment]
I am having the issue with the example provided here copied and pasted https://inquirerpy.readthedocs.io/en/latest/pages/prompts/list.html

I tried with python 3.91 and 3.10 and both were giving me the issue.

```
$  l:/InquirerPyTest/select.py
Traceback (most recent call last):
  File "l:\InquirerPyTest\select.py", line 1, in <module>
    from InquirerPy import inquirer
  File "Python\Python310\lib\site-packages\InquirerPy\__init__.py", line 1, in <module>
    from InquirerPy.resolver import prompt
  File "Python\Python310\lib\site-packages\InquirerPy\resolver.py", line 8, in <module>
    from InquirerPy.prompts.checkbox import CheckboxPrompt
  File "Python\Python310\lib\site-packages\InquirerPy\prompts\__init__.py", line 2, in <module>
    from InquirerPy.prompts.checkbox import CheckboxPrompt
  File "Python\Python310\lib\site-packages\InquirerPy\prompts\checkbox.py", line 4, in <module>
    from prompt_toolkit.validation import ValidationError
  File "Python\Python310\lib\site-packages\prompt_toolkit\__init__.py", line 16, in <module>
    from .application import Application
  File "Python\Python310\lib\site-packages\prompt_toolkit\application\__init__.py", line 1, in <module>
    from .application import Application
  File "Python\Python310\lib\site-packages\prompt_toolkit\application\application.py", line 1, in <module>
    import asyncio
  File "Python\Python310\lib\asyncio\__init__.py", line 8, in <module>
    from .base_events import *
  File "Python\Python310\lib\asyncio\base_events.py", line 23, in <module>
    import socket
  File "Python\Python310\lib\socket.py", line 54, in <module>
    import os, sys, io, selectors
  File "Python\Python310\lib\selectors.py", line 12, in <module>
    import select
  File "l:\InquirerPyTest\select.py", line 1, in <module>
    from InquirerPy import inquirer
  File "Python\Python310\lib\site-packages\InquirerPy\inquirer.py", line 8, in <module>
    from InquirerPy.prompts import CheckboxPrompt as checkbox
ImportError: cannot import name 'CheckboxPrompt' from partially initialized module 'InquirerPy.prompts' (most likely due to a circular import) (C:\...\Python\Python310\lib\site-packages\InquirerPy\prompts\__init__.py)
```

**Comment by kazhala** [comment]
Hi @TStrolia ,

I tried with python3.9.8 within a brand new venv and still could not reproduce the error message you are seeing.

```python
python3 -m venv venv
source venv/bin/activate
pip install InquirerPy
touch test.py
# copied the example from https://inquirerpy.readthedocs.io/en/latest/pages/prompts/list.html
python test.py
```
test.py
```python
from InquirerPy import inquirer
from InquirerPy.base.control import Choice
from InquirerPy.separator import Separator


def main():
    action = inquirer.select(
        message="Select an action:",
        choices=[
            "Upload",
            "Download",
            Choice(value=None, name="Exit"),
        ],
        default=None,
    ).execute()
    if action:
        region = inquirer.select(
            message="Select regions:",
            choices=[
                Choice("ap-southeast-2", name="Sydney"),
                Choice("ap-southeast-1", name="Singapore"),
                Separator(),
                "us-east-1",
                "us-east-2",
            ],
            multiselect=True,
            transformer=lambda result: f"{len(result)} region{'s' if len(result) > 1 else ''} selected",
        ).execute()


if __name__ == "__main__":
    main()
```

Could you also paste the content of `l:/InquirerPyTest/select.py`? Not sure if it could be something in the file or it could be a platform issue for Windows.

The code itself doesn't seem to have any cyclic import upon checking the files, it could also happen to accidental modification to the InquirerPy source code (I purposely tried adding `from InquirerPy.inquirer import checkbox` to `InquirerPy/prompts/list.py` and I could see the same error message). If in any case, could you also try the whole operation in a brand new environment?

Thanks,
Kevin

**Comment by TStrolia** [comment]
The select.py is exactly what you have above. nothing else added. Hmmmm.... Let me try with a venv and see if I am still having issues. I wasn't using one before and went as far as uninstalling all of my pip installs and only installing inquirerpy to see if something got hosed, but maybe a venv will be a different story.

**Comment by kazhala** [comment]
Thanks, I'll have access to a windows machine on Monday to test it if it doesn't work out for you in a new venv.

**Comment by TStrolia** [comment]
Thanks for taking a look. Yeah I am having the same problem in a new project and venv copying and pasting your code from above. Definitely strange

**Comment by kazhala** [comment]
That's a bit unfortunate. I'll give it a shot in python10 tomorrow and otherwise I'll try it on a windows machine on Monday.

In the meantime, since the inquirer module is not working for you. I suggest you should try directly using the prompt classes for now.

`from InquirerPy.prompts import ListPrompt`

**Comment by TStrolia** [comment]
> 

Seems I am having the issue with `from InquirerPy.prompts import ListPrompt` as well. Thats Ok. I will try to sorta mix and match with PyInquirer for now. I tried on my other windows machine as well and am having the same issue. I noticed I was getting an error on install about prompt_toolkit being the wrong version and that it is incompatible so so I manually reinstalled the correct version of prompt_toolkit but now it says it is the wrong version again and that I need the other one so I am not sure what to make of that.

**Comment by kazhala** [comment]
Hi @TStrolia ,

It can't be used alongside with PyInquirer as PyInquirer has a hard cap on prompt-toolkit at version 1.0.3 which is extremely outdated.

I've just tested the snippet on a windows 10 machine with python3.8 and still couldn't reproduce the error...

```python
python -m venv venv
.\venv\Scripts\Activate.ps1
pip install InquirerPy
code .
# copy paste the code from select doc example
```

![image](https://user-images.githubusercontent.com/43941510/142788524-6355a520-f38c-4e15-a004-f7cd2f138930.png)

I'm not too sure what exactly could be the issue that you are facing the circular import error, I will test it with python3.10 just in case but I doubt that would be the issue.

Finally, you may have already tried tons of commands, but just in case, you may also try force-reinstall...

```bash
pip install --upgrade --force-reinstall InquirerPy
```

**Comment by Pluckerpluck** [comment]
The issue is in the stack trace:

```
File "Python\Python310\lib\selectors.py", line 12, in <module>
    import select
  File "l:\InquirerPyTest\select.py", line 1, in <module>
    from InquirerPy import inquirer
```

`select` is [a built in library](https://docs.python.org/3/library/select.html). But you've named your file that, so when the library tries to use `select` it is actually trying to re-import your module.

When you get a circular import, the stack trace is **by far** the most useful debugging tool

**Comment by TStrolia** [comment]
> Hi @TStrolia ,
> 
> It can't be used alongside with PyInquirer as PyInquirer has a hard cap on prompt-toolkit at version 1.0.3 which is extremely outdated.
> 
> I've just tested the snippet on a windows 10 machine with python3.8 and still couldn't reproduce the error...
> 
> ```python
> python -m venv venv
> .\venv\Scripts\Activate.ps1
> pip install InquirerPy
> code .
> # copy paste the code from select doc example
> ```
> 
> ![image](https://user-images.githubusercontent.com/43941510/142788524-6355a520-f38c-4e15-a004-f7cd2f138930.png)
> 
> I'm not too sure what exactly could be the issue that you are facing the circular import error, I will test it with python3.10 just in case but I doubt that would be the issue.
> 
> Finally, you may have already tried tons of commands, but just in case, you may also try force-reinstall...
> 
> ```shell
> pip install --upgrade --force-reinstall InquirerPy
> ```

Hey sorry for the very late reply. Stepped away for a little while. Thank you yeah that unfortunately wasn't the issue.

> The issue is in the stack trace:
> 
> ```
> File "Python\Python310\lib\selectors.py", line 12, in <module>
>     import select
> File "l:\InquirerPyTest\select.py", line 1, in <module>
>     from InquirerPy import inquirer
> ```
> 
> `select` is [a built in library](https://docs.python.org/3/library/select.html). But you've named your file that, so when the module (selectors) tries to use `select` it is actually trying to re-import your module rather than the built-in.
> 
> Rename `select.py` and your troubles will go away.
> 
> When you get a circular import, the stack trace is **by far** the most useful debugging tool.
> 
> Note: This is why it's good practice to **always** drop your code under a package directory. Stops any potential conflicts.

This however seems to be it. It is funny because this is the first time i have done something like that. Just made sense to keep a reference on my local machine and name the files accordingly so I don't have to keep jumping to the docs, and here I am scratching my head why that wasn't working. I suppose having this issue for the first time on someone else's package where there is at least support is the best way to have learned that lesson. Thank you both!
