### ISSUE TITLE
Feature: Add a toggle All option for checkbox  

### ISSUE THREAD

**Issue by Akusem** [kazhala/InquirerPy#29]
Hi,
First, thank you for developing InquirerPy, I find it really user-friendly and Pythonic with the alternative syntax !
 
I'm making this issue because I've encountered a situation that the library doesn't seem to handle (at least to my knowledge) which could be useful I think.
I'm currently using the checkbox prompt to choose which step a pipeline should be executed, but as it contains many steps, having a working "toggle all" button would be superb.

Example:

![image](https://user-images.githubusercontent.com/24433720/142911430-45a1f928-8937-4e44-8945-e1f0b9d1c781.png)

**Comment by kazhala** [comment]
Hi @Akusem ,

Not sure if you are aware of the keybinding option you could set for the prompt. For the checkbox prompt, there's an existing built-in keybinding "alt-r" and "ctrl-r" to toggle all of the options. This is documented [here](https://inquirerpy.readthedocs.io/en/latest/pages/prompts/list.html#keybindings).

You could customise the keybinding to your preference and also use the parameter `long_instruction` or `instruction` to hint the keybindings to the user.

```python
from InquirerPy import inquirer

result = inquirer.select(message="Steps to execute", choices=[1, 2, 3], instruction="(ctrl-r toggle)", multiselect=True).execute()
```

Let me know if that satisfies your use case. Personally, I think having both keybindings and a dedicated option to toggle all could be a little redundant.

Thanks,
Kevin

**Comment by Akusem** [comment]
Thanks for your help @kazhala.

Yes, I wasn't aware of the keybinding option, I didn't take it into account when using the select prompt, and it isn't present in the checkbox docs.
I know it's my fault for not reading this part of the docs, but I would recommend putting some word inside this part of the docs as I will certainly not be the only user to forget about the keybinding.

> You could customise the keybinding to your preference and also use the parameter long_instruction or instruction to hint the keybindings to the user.

Perfect recommendation, will do that !

> Let me know if that satisfies your use case. Personally, I think having both keybindings and a dedicated option to toggle all could be a little redundant.

Absolutely, and I agree concerning the redundancy, feel free to close the issue.

**Comment by kazhala** [comment]
Hi @Akusem ,

Thanks for the suggestion. I agree, I think having a bit more illustration on the checkbox keybindings could be more helpful instead of just linking to the other page.

I'll work on it first and then close this issue.

Thanks,
Kevin

**Comment by kazhala** [comment]
Docs added. Thanks
