### ISSUE TITLE
[Feature Request] Disable qmark

### ISSUE THREAD

**Issue by jfilipedias** [kazhala/InquirerPy#3]
Hey guys, how are you? Thank you for the incredible work with this project.

I am using the project and I would like to know if it is possible to disable qmark before a question. I actually left an empty string in the arg as `qmark=''`, but the inquirer still adds a space before the question. At the terminal, it appears that the question is indented incorrectly. It would be nice if you could disable qmark or just not add it to the prompt message if the string is empty.

If so, I can open and submit a PR. What do you think?

**Comment by kazhala** [comment]
Hi @jfilipedias,

Thanks for raising this up. Indeed the current implementation didn't take your scenario into account. I'm happy with your suggestions and would like to include that in the next release.

PR is always welcome, you'd wanna look into the following [lines](https://github.com/kazhala/InquirerPy/blob/9f67125f808cbe6a73ab3cb652f35faba3f3443e/InquirerPy/base.py#L193-L194).

Thanks,
Kevin

**Comment by jfilipedias** [comment]
Hey @kazhala, how's it going? I opened the PR #4
