### ISSUE TITLE
FilePath (on Windows) doesn't autocomplete past the first directory using /

### ISSUE THREAD

**Issue by Pluckerpluck** [kazhala/InquirerPy#32]
When using the `filepath` on windows, it autocompletes with a forward slash. It doesn't actually add the foward slash when you hit tab, but it's there visually in the autocomplete. However, if you use a forward slash, the system no longer autocompletes. You **must** type a `\` despite what the prompt said.

In reality, both `/` and `\` should be accepted on Windows. But at minimum, the prompt should show a `\`.

**Comment by kazhala** [comment]
Hi @Pluckerpluck ,

Thanks for reporting, indeed these were not taken into consideration while implementing the prompt as I do not work with Windows at the time.

I'll do some testing on my work laptop and work on it.

Thanks,
Kevin

**Comment by kazhala** [comment]
Apologies for the delay on this action. It is currently included in 0.3.3 release, feel free to open it if you still encounter issues. Thanks
