### ISSUE TITLE
[Feature Request] 'exact' parameter for fuzzy prompt

### ISSUE THREAD

**Issue by DeadNews** [kazhala/InquirerPy#34]
Like https://github.com/dahlia/iterfzf#user-content-iterfzfiterfzfiterable-options
```markdown
``exact``
   ``False`` for fuzzy matching, and ``True`` for exact matching.

   ``False`` by default.
```
ref: https://github.com/kazhala/pfzy/blob/71e4dae11020d31d9baf0b25df8ee95836c6787c/docs/pages/usage.md#substr_scorer

**Comment by kazhala** [comment]
Hi @DeadNews ,

Thanks for the suggestion. It is now included in the latest release.

You can view the docs [here](https://inquirerpy.readthedocs.io/en/latest/pages/prompts/fuzzy.html#exact-sub-string-match).

Thanks

**Comment by DeadNews** [comment]
Thanks. All works.

**Comment by DeadNews** [comment]
@kazhala
Thanks. All works.
