### ISSUE TITLE
TypeError: 'InquirerPyStyle' object is not a mapping

### ISSUE THREAD

**Issue by SolebaySharp** [kazhala/InquirerPy#37]
Trying to run a basic `rawlist` question and the following error is occurring:

``TypeError: 'InquirerPyStyle' object is not a mapping``

If you could have a look when you are next free I would appreciate the help.

To replicate:

```
#!/usr/bin/env bash

python3.9 -m venv test_env
source test_env/bin/activate
pip3 install InquirerPy
python3 "/home/solebay/Projects/tests/test_file_x.py"
```

Script:

```
#!/usr/bin/env python

"""Simple reproducible example"""

from InquirerPy import prompt
from InquirerPy.base.control import Choice
from InquirerPy.separator import Separator
from InquirerPy import get_style

test_style = get_style({"separator": '#6C6C6C'}, style_override=True)

my_question = [
    {
        'type': 'rawlist',
        'name': "test",
        'message': "test question",
        'choices':  [
                    'I',
                    'II',
                    'III',
                    ],
    }
]
answer = prompt(my_question, style=test_style)
```
Running just...

`answer = prompt(my_question)`

allows the question to work without custom styling.

___________

n.b. In a possiby related issue, running...

```
from InquirerPy import get_style
from InquirerPy import inquirer

style = get_style({"questionmark": "#ffffff", "answer": "#000000"}, style_override=False)
result = inquirer.confirm(message="Confirm?", style=style)
```

...as per the example in the [style documentation](https://inquirerpy.readthedocs.io/en/latest/pages/style.html) does nothing and returns no error message. If it's working correctly and its just an example for the style guide feel free to delete this part of the question or I can do it myself.

**Comment by kazhala** [comment]
Hi @SolebaySharp ,

Thanks for reporting. I will take a look at the exception you are getting tomorrow.

But for the final comment on the possibility related part, seems to be me being careless on the doc. Should include `.execute()`.

```
....
inquirer.rawlist(...).execute()
```

Lemme know if you have encountered any further issues after adding execute.

Thanks,
Kevin

**Comment by kazhala** [comment]
From another brief look, just on the high level. You may be encountering this issue because you are trying to use `get_style` with Classic Syntax.

With classic syntax (prompt), you don't need the get_style, rather just pass the style dictionary to it.

If you take a look further down the [Alternate Syntax](https://inquirerpy.readthedocs.io/en/latest/pages/style.html#alternate-syntax), it mentions the `get_style` is to be used here.

However I do notice the missing `execute()` in the example. I'll update it.

Thanks

**Comment by SolebaySharp** [comment]
Thank you Kevin, I really appreciate the assistance. 

I'll try to fix my code tonight and close this.

**Comment by SolebaySharp** [comment]
@kazhala just checked and using:

`test_style = {"separator": '#6C6C6C'}
`
Gets everything working. Once everything is running using InquirerPy not PyInquirer, I'll create a new version and transition everything into the alternate syntax. I'll close this, thank you.
