### ISSUE TITLE
Ctrl + c not captured properly when using register_kb

### ISSUE THREAD

**Issue by Quiquex** [kazhala/InquirerPy#42]
Given the following code

```
import sys
from InquirerPy import inquirer

fav_lang_select = inquirer.select(
    message="What's your favourite programming language:",
    choices=["Go", "Python", "Rust", "JavaScript"],
)


@fav_lang_select.register_kb("c-c")
def custom_ctrl_c(event):
    print("I'm exiting")
    sys.exit(0)


fav_lang_select.execute()

confirm = inquirer.confirm(message="Confirm?").execute()
```

Pressing ctrl+c isn't captured and a standard Keyboard Interrupt is received.
Setting another keyboard shortcut (ie: ctrl+y) works as supposed.
Experiencing this on Python 3.8.8 (Windows 10) and Python 3.8.10 (Linux)

**Comment by kazhala** [comment]
Hi @Quiquex ,

Apologies for the late response. The `c-c` is binded by default to raise interrupt hence why you are experiencing this. The keybindings engine doesn't expose enough parameter to have you overwrite other bindings (I might look into this and expose a bit more).

For now, please disable the `c-c` keybindings.
```python
import sys

from InquirerPy import inquirer

fav_lang_select = inquirer.select(
    message="What's your favourite programming language:",
    choices=["Go", "Python", "Rust", "JavaScript"],
    keybindings={"interrupt": []},  # disable the default interrupt keybindings
)


@fav_lang_select.register_kb("c-c")
def custom_ctrl_c(event):
    print("I'm exiting")
    sys.exit(0)


fav_lang_select.execute()

confirm = inquirer.confirm(message="Confirm?").execute()
```

Refer to the [doc](https://inquirerpy.readthedocs.io/en/latest/pages/kb.html#keybindings) for a list of default keybindings.

Thanks,
Kevin
