### ISSUE TITLE
Selected color

### ISSUE THREAD

**Issue by 9Samzer** [kazhala/InquirerPy#43]
Hey ! 
Is there a way to change current blue color for selection in Select ? Thxx

**Comment by kazhala** [comment]
Hi @9Samzer ,

The current select is under the `pointer` style class, you can change it like this.

```python
from InquirerPy import inquirer
from InquirerPy.base.control import Choice
from InquirerPy.utils import get_style

action = inquirer.select(
    message="Select an action:",
    choices=[
        "Upload",
        "Download",
        Choice(value=None, name="Exit"),
    ],
    default=None,
    style=get_style({"pointer": "yellow"}),
).execute()
```

This will change the selection to yellow. Please refer to [doc](https://inquirerpy.readthedocs.io/en/latest/pages/style.html#style) for more info.

Thanks,
Kevin
