### ISSUE TITLE
Missing py.typed marker file for PEP 561

### ISSUE THREAD

**Issue by jonemo** [kazhala/InquirerPy#45]
When type checking projects that depend on InquirerPy with `mypy` with default settings, the following error results in a type checking failure:

```
Skipping analyzing "InquirerPy": module is installed, but missing library stubs or py.typed marker
```

To reproduce:

1. Install `InquirerPy` as dependency into a project
2. Run `mypy my-project-directory` to type check the project

Related information: 
* PEP 561: https://www.python.org/dev/peps/pep-0561/
* mypy docs about the error: https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker

**Comment by kazhala** [comment]
> Hi jonemo ,
> 
> Thanks again for doing this. I should have touched up in the issue ticket for this. No not your changes broke the pyright lints, think pyright updated some checks around `Optional[XXX]` which I need to update the codebase to align with that.
> 
> I've been quite busy for the last few months and should have fixed the pyright thing first. I'll close your issue once I fix the linting and make a quick release.
> 
> Thanks

cross posting here ..
