### ISSUE TITLE
Typo in example_pizza.py 

### ISSUE THREAD

**Issue by piyush-das** [kazhala/InquirerPy#5]
Hi,

There is a minor typo in the pizza example where the list should reference the element as `x[0]` rather than `x["0"]`.
https://github.com/kazhala/InquirerPy/blob/cff560fe5e7b13eb903341d8e2c1ea4d025304b3/examples/example_pizza.py#L20

On a side note, I believe pydantic would go really well with InquirerPy as building a CLI around configurations does happen a lot and then  the validators from pydantic could as well kick in. Having said that , the customizability options provided by this package is just awesome, loving it :)

Thanks

**Comment by kazhala** [comment]
Hi @piyush-das ,

Thanks for pointing it out. Indeed it was a typo.

Thanks,
Kevin

**Comment by kazhala** [comment]
Hi @piyush-das ,

Sorry missed your second part of the message. I checked out pydantic and it does seem like a pretty good tool to validate the classic style parameter. I'll look into it. Thanks for the suggestion.

Thanks,
Kevin
