### ISSUE TITLE
[Feature Request] Default selections for Checkbox

### ISSUE THREAD

**Issue by piyush-das** [kazhala/InquirerPy#8]
Hi,

Presently there is no way to have certain checkboxes pre-enabled like sanity "default" configuration. Would be great if we can have the same.

The default argument in the checkbox only changes the location selector arrow index, however from an API perspective for checkbox, "default" should ideally mean the choices  which are selected/enabled by default. But then this is subjective and depends on personal preferences.

Thanks

**Comment by kazhala** [comment]
Hi @piyush-das ,

You can actually pre-enable checkbox, this feature is currently present. You can have look at this checkbox example https://github.com/kazhala/InquirerPy/blob/master/examples/example_checkbox.py.

Each item in the checkbox list supports a key called `enabled`. If this is `True` then the checkbox is enabled by default.

You are correct that the default argument only changes the selection index.

Thanks,
Kevin
