### ISSUE TITLE
[Question] Option to disable selector from rolling over to first choice

### ISSUE THREAD

**Issue by piyush-das** [kazhala/InquirerPy#9]
Hi,

Currently on trying to scroll down in a select or checkbox prompt, after the end of the choices is encountered, the selector reverts to the first index. Is there a way we can disable this?

Thanks

**Comment by kazhala** [comment]
Hi @piyush-das ,

At the moment no, but I agree there should be an option to disable it. It would be a fairly simple tweak, I will add that customization over the weekend.

Thanks,
Kevin

**Comment by kazhala** [comment]
I've added a parameter called `cycle` in all list type prompts. It's `True` by default, you can achieve the behaviour you want by setting it to `False`.

I'll make a new release tmr.

Thanks,
Kevin

**Comment by kazhala** [comment]
Hi @piyush-das,

Apologies for the delay, the new version 0.2.1 is released.

Thanks,
Kevin
